#!/bin/sh
# config syntax
# backupdir="~/net/p/data/backuper"
# backthisup="dir1 dir2"
# exclude="dir3 /path/to/dir *.tmp"
# rsyncopt=" --exclude-from=.excludelist"
# postcmd="eg: mv  $backupdir blah  "

BACKUPCONF="$HOME/.backthisup.conf"


if [[ -e $BACKUPCONF ]]; then
	source $BACKUPCONF
	date=$(date "+%d-%m-%y_%H:%M")

	#build exclude list
	for _exclude in $exclude; do
		_excludelst="${_excludelst} --exclude $_exclude "
	done

	backup=${destination}/$(hostname)-${date}	
	RSYNC_PARAM="-RaP $_excludelst --link-dest=$destination/current $source $backup"

	echo "(i) back this up: $source"
	echo "(i) destination folder: $backup"
	echo "(i) excluding $_excludelst"
	sleep 1
	
	echo "executing: rsync $rsyncopt $RSYNC_PARAM"
	rsync $rsyncopt $RSYNC_PARAM
	
	rm -f $destination/current
	echo "linking newest backup with to current symlink"
	ln -s $backup $destination/current

	[[ $postcmd ]] && $postcmd && echo "(i) post cmd executed"
	exit 0
else
	echo "(!) sorry no config found. view script source for more informations"
	exit 1
fi
