#!/bin/sh
#config syntax:
# source="/boot /etc /home/kru"
# destination="/media/datasd/data/backups/"
# exclude=""
# rsyncopt=" --exclude-from=/home/kru/.kbackupexclude"
# postcmd="eg: mv  $backupdir blah  "

BACKUPCONF="/home/kru/.backthisup.conf"


if [[ -e $BACKUPCONF ]]; then
	source $BACKUPCONF
	date=$(date "+%d-%m-%y_%H:%M")

	#build exclude list
	#exclude=$(cat $excludefile)
	exclude=$excludefile
	for _exclude in $exclude; do
		_excludelst="${_excludelst} --exclude-from $_exclude "
	done

	backup=${destination}/$(hostname)-${date}	
	RSYNC_PARAM="-RaP $_excludelst --link-dest=$destination/current $source $backup"

	echo "(i) back this up: $source"
	echo "(i) destination folder: $backup"
	echo "(i) excluding $_excludelst"
	sleep 1
	echo "executing: sudo rsync $rsyncopt $RSYNC_PARAM"
	sudo rsync $rsyncopt $RSYNC_PARAM
	exitcode=$?

	echo "(i) RSYNC Exit Status: $exitcode" 
	if [[ $exitcode == 0 ]]; then
		rm -f $destination/current
		echo "linking newest backup with to current symlink"
		ln -s $backup $destination/current
		[[ $postcmd ]] && $postcmd && echo "(i) post cmd executed"
	fi

	exit 0
else
	echo "(!) sorry no config found. view script source for more informations"
	exit 1
fi
