#!/usr/bin/python

#path = '/mnt/c400/movies/.norp/new/'
patharr= ['/home/kru/multimedia/movies/.norp', '/mnt/c400/movies/.norp/', '/mnt/c400/movies/.norp/new/' ]
#path = '/home/kru/movies/.norp'
player = 'mplayer -fs '

import random, os, dircache

path = random.choice(patharr)
list = dircache.listdir(path)

def playthis(file):
	command = player + path +'/'+ file
	os.system(command) 

while ( 1 ):
	next = raw_input('next [y/n] or del [d]:')
	if next.lower() == 'n':
		break
	elif next.lower() == 'd':
		check = raw_input('sure Y/n:')
		if check.lower() == 'y':
			print "deleting %s" % rndfile 
			delfile = 'rm ' + path + '/' + rndfile
			os.system(delfile)
	else:
		rndfile = random.choice(list)
		lastrndfile = rndfile
		playthis(rndfile)
		next=0

